// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: proto/components/search/filter.proto

package search

import (
	primitives "github.com/thousight/mark-wen-space-schema/markwen.space/pb/proto/primitives"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values []*FilterRequestValue `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_components_search_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_components_search_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_components_search_filter_proto_rawDescGZIP(), []int{0}
}

func (x *FilterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FilterRequest) GetValues() []*FilterRequestValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type FilterRequestValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Values:
	//
	//	*FilterRequestValue_Value
	//	*FilterRequestValue_DateTimeRange
	Values isFilterRequestValue_Values `protobuf_oneof:"values"`
}

func (x *FilterRequestValue) Reset() {
	*x = FilterRequestValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_components_search_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterRequestValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequestValue) ProtoMessage() {}

func (x *FilterRequestValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_components_search_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequestValue.ProtoReflect.Descriptor instead.
func (*FilterRequestValue) Descriptor() ([]byte, []int) {
	return file_proto_components_search_filter_proto_rawDescGZIP(), []int{1}
}

func (m *FilterRequestValue) GetValues() isFilterRequestValue_Values {
	if m != nil {
		return m.Values
	}
	return nil
}

func (x *FilterRequestValue) GetValue() string {
	if x, ok := x.GetValues().(*FilterRequestValue_Value); ok {
		return x.Value
	}
	return ""
}

func (x *FilterRequestValue) GetDateTimeRange() *primitives.DateTimeRange {
	if x, ok := x.GetValues().(*FilterRequestValue_DateTimeRange); ok {
		return x.DateTimeRange
	}
	return nil
}

type isFilterRequestValue_Values interface {
	isFilterRequestValue_Values()
}

type FilterRequestValue_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type FilterRequestValue_DateTimeRange struct {
	DateTimeRange *primitives.DateTimeRange `protobuf:"bytes,2,opt,name=dateTimeRange,proto3,oneof"`
}

func (*FilterRequestValue_Value) isFilterRequestValue_Values() {}

func (*FilterRequestValue_DateTimeRange) isFilterRequestValue_Values() {}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	JsonPath string `protobuf:"bytes,3,opt,name=json_path,json=jsonPath,proto3" json:"json_path,omitempty"`
	// Types that are assignable to Types:
	//
	//	*Filter_Selection
	//	*Filter_Keywords
	//	*Filter_AvailableDateRage
	Types isFilter_Types `protobuf_oneof:"types"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_components_search_filter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_components_search_filter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_components_search_filter_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Filter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Filter) GetJsonPath() string {
	if x != nil {
		return x.JsonPath
	}
	return ""
}

func (m *Filter) GetTypes() isFilter_Types {
	if m != nil {
		return m.Types
	}
	return nil
}

func (x *Filter) GetSelection() *Selection {
	if x, ok := x.GetTypes().(*Filter_Selection); ok {
		return x.Selection
	}
	return nil
}

func (x *Filter) GetKeywords() *Keywords {
	if x, ok := x.GetTypes().(*Filter_Keywords); ok {
		return x.Keywords
	}
	return nil
}

func (x *Filter) GetAvailableDateRage() *primitives.DateTimeRange {
	if x, ok := x.GetTypes().(*Filter_AvailableDateRage); ok {
		return x.AvailableDateRage
	}
	return nil
}

type isFilter_Types interface {
	isFilter_Types()
}

type Filter_Selection struct {
	Selection *Selection `protobuf:"bytes,4,opt,name=selection,proto3,oneof"`
}

type Filter_Keywords struct {
	Keywords *Keywords `protobuf:"bytes,5,opt,name=keywords,proto3,oneof"`
}

type Filter_AvailableDateRage struct {
	AvailableDateRage *primitives.DateTimeRange `protobuf:"bytes,6,opt,name=available_date_rage,json=availableDateRage,proto3,oneof"`
}

func (*Filter_Selection) isFilter_Types() {}

func (*Filter_Keywords) isFilter_Types() {}

func (*Filter_AvailableDateRage) isFilter_Types() {}

type Selection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Single  bool               `protobuf:"varint,1,opt,name=single,proto3" json:"single,omitempty"`
	Options []*SelectionOption `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *Selection) Reset() {
	*x = Selection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_components_search_filter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_components_search_filter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_proto_components_search_filter_proto_rawDescGZIP(), []int{3}
}

func (x *Selection) GetSingle() bool {
	if x != nil {
		return x.Single
	}
	return false
}

func (x *Selection) GetOptions() []*SelectionOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type SelectionOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Selected bool   `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
}

func (x *SelectionOption) Reset() {
	*x = SelectionOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_components_search_filter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionOption) ProtoMessage() {}

func (x *SelectionOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_components_search_filter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionOption.ProtoReflect.Descriptor instead.
func (*SelectionOption) Descriptor() ([]byte, []int) {
	return file_proto_components_search_filter_proto_rawDescGZIP(), []int{4}
}

func (x *SelectionOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SelectionOption) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SelectionOption) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

type Keywords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keywords    []string `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Placeholder string   `protobuf:"bytes,2,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
}

func (x *Keywords) Reset() {
	*x = Keywords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_components_search_filter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keywords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keywords) ProtoMessage() {}

func (x *Keywords) ProtoReflect() protoreflect.Message {
	mi := &file_proto_components_search_filter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keywords.ProtoReflect.Descriptor instead.
func (*Keywords) Descriptor() ([]byte, []int) {
	return file_proto_components_search_filter_proto_rawDescGZIP(), []int{5}
}

func (x *Keywords) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Keywords) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

var File_proto_components_search_filter_proto protoreflect.FileDescriptor

var file_proto_components_search_filter_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x1a, 0x1c,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x73,
	0x2f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x0d,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x22, 0x79, 0x0a, 0x12, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x41, 0x0a, 0x0d, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69,
	0x76, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x84, 0x02, 0x0a,
	0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x50, 0x61, 0x74, 0x68, 0x12, 0x31, 0x0a, 0x09, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a,
	0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x48, 0x00, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x4b, 0x0a,
	0x13, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x72, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x69,
	0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x11, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x44, 0x61, 0x74, 0x65, 0x52, 0x61, 0x67, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x22, 0x56, 0x0a, 0x09, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x53, 0x0a, 0x0f, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x22, 0x48, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x42, 0x55, 0x5a, 0x53, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x69, 0x67,
	0x68, 0x74, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x2d, 0x77, 0x65, 0x6e, 0x2d, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x77, 0x65, 0x6e,
	0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_components_search_filter_proto_rawDescOnce sync.Once
	file_proto_components_search_filter_proto_rawDescData = file_proto_components_search_filter_proto_rawDesc
)

func file_proto_components_search_filter_proto_rawDescGZIP() []byte {
	file_proto_components_search_filter_proto_rawDescOnce.Do(func() {
		file_proto_components_search_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_components_search_filter_proto_rawDescData)
	})
	return file_proto_components_search_filter_proto_rawDescData
}

var file_proto_components_search_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_components_search_filter_proto_goTypes = []interface{}{
	(*FilterRequest)(nil),            // 0: search.FilterRequest
	(*FilterRequestValue)(nil),       // 1: search.FilterRequestValue
	(*Filter)(nil),                   // 2: search.Filter
	(*Selection)(nil),                // 3: search.Selection
	(*SelectionOption)(nil),          // 4: search.SelectionOption
	(*Keywords)(nil),                 // 5: search.Keywords
	(*primitives.DateTimeRange)(nil), // 6: primitives.DateTimeRange
}
var file_proto_components_search_filter_proto_depIdxs = []int32{
	1, // 0: search.FilterRequest.values:type_name -> search.FilterRequestValue
	6, // 1: search.FilterRequestValue.dateTimeRange:type_name -> primitives.DateTimeRange
	3, // 2: search.Filter.selection:type_name -> search.Selection
	5, // 3: search.Filter.keywords:type_name -> search.Keywords
	6, // 4: search.Filter.available_date_rage:type_name -> primitives.DateTimeRange
	4, // 5: search.Selection.options:type_name -> search.SelectionOption
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_components_search_filter_proto_init() }
func file_proto_components_search_filter_proto_init() {
	if File_proto_components_search_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_components_search_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_components_search_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterRequestValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_components_search_filter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_components_search_filter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Selection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_components_search_filter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectionOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_components_search_filter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Keywords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_components_search_filter_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*FilterRequestValue_Value)(nil),
		(*FilterRequestValue_DateTimeRange)(nil),
	}
	file_proto_components_search_filter_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Filter_Selection)(nil),
		(*Filter_Keywords)(nil),
		(*Filter_AvailableDateRage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_components_search_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_components_search_filter_proto_goTypes,
		DependencyIndexes: file_proto_components_search_filter_proto_depIdxs,
		MessageInfos:      file_proto_components_search_filter_proto_msgTypes,
	}.Build()
	File_proto_components_search_filter_proto = out.File
	file_proto_components_search_filter_proto_rawDesc = nil
	file_proto_components_search_filter_proto_goTypes = nil
	file_proto_components_search_filter_proto_depIdxs = nil
}
