name: Pull Request Testing

on:
  pull_request:
    branches:
      - main

jobs:
  build_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Protoc
        uses: arduino/setup-protoc@v2

      - name: Test Golang
        run: make go