name: Pull Request Testing

on:
  pull_request:
    branches:
      - main

jobs:
  build_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v4
      
      - name: Setup Protoc
        uses: arduino/setup-protoc@v2

      - name: Setup protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Test Golang
        run: make go