name: Pull Request Testing

on:
  pull_request:
    branches:
      - main

jobs:
  build_ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Ppotoc
        uses: arduino/setup-protoc@v2
     
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
     
      - name: Test typescript
        run: make ts