name: Pull Request Testing

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
     
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
     
      - name: Test TypeScript
        run: make ts