name: Build and publish TypeScript

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup protoc
        uses: arduino/setup-protoc@v2
      
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Build app
        run: make ts
      
      - name: Semantic release
        run: npx semantic-release