// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: proto/services/pages/home_page.proto

package services

import (
	components "github.com/thousight/mark-wen-space-schema/pb/proto/components"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HomePageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HomePageRequest) Reset() {
	*x = HomePageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_services_pages_home_page_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomePageRequest) ProtoMessage() {}

func (x *HomePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_pages_home_page_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomePageRequest.ProtoReflect.Descriptor instead.
func (*HomePageRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_pages_home_page_proto_rawDescGZIP(), []int{0}
}

func (x *HomePageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HomePageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata  *components.PageMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	IntroCard *components.IntroCard    `protobuf:"bytes,2,opt,name=intro_card,json=introCard,proto3" json:"intro_card,omitempty"`
}

func (x *HomePageResponse) Reset() {
	*x = HomePageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_services_pages_home_page_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomePageResponse) ProtoMessage() {}

func (x *HomePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_pages_home_page_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomePageResponse.ProtoReflect.Descriptor instead.
func (*HomePageResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_pages_home_page_proto_rawDescGZIP(), []int{1}
}

func (x *HomePageResponse) GetMetadata() *components.PageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HomePageResponse) GetIntroCard() *components.IntroCard {
	if x != nil {
		return x.IntroCard
	}
	return nil
}

var File_proto_services_pages_home_page_proto protoreflect.FileDescriptor

var file_proto_services_pages_home_page_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x70, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x1a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x25, 0x0a, 0x0f, 0x48, 0x6f, 0x6d, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7e, 0x0a, 0x10, 0x48, 0x6f, 0x6d, 0x65, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x34, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x43, 0x61, 0x72, 0x64, 0x52, 0x09, 0x69, 0x6e,
	0x74, 0x72, 0x6f, 0x43, 0x61, 0x72, 0x64, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x69, 0x67, 0x68, 0x74, 0x2f,
	0x6d, 0x61, 0x72, 0x6b, 0x2d, 0x77, 0x65, 0x6e, 0x2d, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2d, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_services_pages_home_page_proto_rawDescOnce sync.Once
	file_proto_services_pages_home_page_proto_rawDescData = file_proto_services_pages_home_page_proto_rawDesc
)

func file_proto_services_pages_home_page_proto_rawDescGZIP() []byte {
	file_proto_services_pages_home_page_proto_rawDescOnce.Do(func() {
		file_proto_services_pages_home_page_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_services_pages_home_page_proto_rawDescData)
	})
	return file_proto_services_pages_home_page_proto_rawDescData
}

var file_proto_services_pages_home_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_services_pages_home_page_proto_goTypes = []interface{}{
	(*HomePageRequest)(nil),         // 0: services.HomePageRequest
	(*HomePageResponse)(nil),        // 1: services.HomePageResponse
	(*components.PageMetadata)(nil), // 2: components.PageMetadata
	(*components.IntroCard)(nil),    // 3: components.IntroCard
}
var file_proto_services_pages_home_page_proto_depIdxs = []int32{
	2, // 0: services.HomePageResponse.metadata:type_name -> components.PageMetadata
	3, // 1: services.HomePageResponse.intro_card:type_name -> components.IntroCard
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_services_pages_home_page_proto_init() }
func file_proto_services_pages_home_page_proto_init() {
	if File_proto_services_pages_home_page_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_services_pages_home_page_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomePageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_services_pages_home_page_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomePageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_services_pages_home_page_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_services_pages_home_page_proto_goTypes,
		DependencyIndexes: file_proto_services_pages_home_page_proto_depIdxs,
		MessageInfos:      file_proto_services_pages_home_page_proto_msgTypes,
	}.Build()
	File_proto_services_pages_home_page_proto = out.File
	file_proto_services_pages_home_page_proto_rawDesc = nil
	file_proto_services_pages_home_page_proto_goTypes = nil
	file_proto_services_pages_home_page_proto_depIdxs = nil
}
