// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: proto/services/pages/software_page.proto

package services

import (
	components "github.com/thousight/mark-wen-space-schema/markwen.space/schema/components"
	search "github.com/thousight/mark-wen-space-schema/markwen.space/schema/components/search"
	content "github.com/thousight/mark-wen-space-schema/markwen.space/schema/content"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SoftwarePageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchFunctionsRequest *search.SearchFunctionsRequest `protobuf:"bytes,1,opt,name=search_functions_request,json=searchFunctionsRequest,proto3" json:"search_functions_request,omitempty"`
}

func (x *SoftwarePageRequest) Reset() {
	*x = SoftwarePageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_services_pages_software_page_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoftwarePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwarePageRequest) ProtoMessage() {}

func (x *SoftwarePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_pages_software_page_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwarePageRequest.ProtoReflect.Descriptor instead.
func (*SoftwarePageRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_pages_software_page_proto_rawDescGZIP(), []int{0}
}

func (x *SoftwarePageRequest) GetSearchFunctionsRequest() *search.SearchFunctionsRequest {
	if x != nil {
		return x.SearchFunctionsRequest
	}
	return nil
}

type SoftwarePageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata                *components.PageMetadata        `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SearchFunctionsResponse *search.SearchFunctionsResponse `protobuf:"bytes,2,opt,name=search_functions_response,json=searchFunctionsResponse,proto3" json:"search_functions_response,omitempty"`
	Softwares               []*content.Software             `protobuf:"bytes,3,rep,name=softwares,proto3" json:"softwares,omitempty"`
}

func (x *SoftwarePageResponse) Reset() {
	*x = SoftwarePageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_services_pages_software_page_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SoftwarePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwarePageResponse) ProtoMessage() {}

func (x *SoftwarePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_pages_software_page_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwarePageResponse.ProtoReflect.Descriptor instead.
func (*SoftwarePageResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_pages_software_page_proto_rawDescGZIP(), []int{1}
}

func (x *SoftwarePageResponse) GetMetadata() *components.PageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SoftwarePageResponse) GetSearchFunctionsResponse() *search.SearchFunctionsResponse {
	if x != nil {
		return x.SearchFunctionsResponse
	}
	return nil
}

func (x *SoftwarePageResponse) GetSoftwares() []*content.Software {
	if x != nil {
		return x.Softwares
	}
	return nil
}

var File_proto_services_pages_software_page_proto protoreflect.FileDescriptor

var file_proto_services_pages_software_page_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x70, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x1a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x13, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72,
	0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x58, 0x0a, 0x18,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x16,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xda, 0x01, 0x0a, 0x14, 0x53, 0x6f, 0x66, 0x74, 0x77,
	0x61, 0x72, 0x65, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x34, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x50,
	0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x5b, 0x0a, 0x19, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x17, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e,
	0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x52, 0x09, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61,
	0x72, 0x65, 0x73, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x68, 0x6f, 0x75, 0x73, 0x69, 0x67, 0x68, 0x74, 0x2f, 0x6d, 0x61, 0x72, 0x6b,
	0x2d, 0x77, 0x65, 0x6e, 0x2d, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x77, 0x65, 0x6e, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_services_pages_software_page_proto_rawDescOnce sync.Once
	file_proto_services_pages_software_page_proto_rawDescData = file_proto_services_pages_software_page_proto_rawDesc
)

func file_proto_services_pages_software_page_proto_rawDescGZIP() []byte {
	file_proto_services_pages_software_page_proto_rawDescOnce.Do(func() {
		file_proto_services_pages_software_page_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_services_pages_software_page_proto_rawDescData)
	})
	return file_proto_services_pages_software_page_proto_rawDescData
}

var file_proto_services_pages_software_page_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_services_pages_software_page_proto_goTypes = []interface{}{
	(*SoftwarePageRequest)(nil),            // 0: services.SoftwarePageRequest
	(*SoftwarePageResponse)(nil),           // 1: services.SoftwarePageResponse
	(*search.SearchFunctionsRequest)(nil),  // 2: search.SearchFunctionsRequest
	(*components.PageMetadata)(nil),        // 3: components.PageMetadata
	(*search.SearchFunctionsResponse)(nil), // 4: search.SearchFunctionsResponse
	(*content.Software)(nil),               // 5: content.Software
}
var file_proto_services_pages_software_page_proto_depIdxs = []int32{
	2, // 0: services.SoftwarePageRequest.search_functions_request:type_name -> search.SearchFunctionsRequest
	3, // 1: services.SoftwarePageResponse.metadata:type_name -> components.PageMetadata
	4, // 2: services.SoftwarePageResponse.search_functions_response:type_name -> search.SearchFunctionsResponse
	5, // 3: services.SoftwarePageResponse.softwares:type_name -> content.Software
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_services_pages_software_page_proto_init() }
func file_proto_services_pages_software_page_proto_init() {
	if File_proto_services_pages_software_page_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_services_pages_software_page_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoftwarePageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_services_pages_software_page_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SoftwarePageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_services_pages_software_page_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_services_pages_software_page_proto_goTypes,
		DependencyIndexes: file_proto_services_pages_software_page_proto_depIdxs,
		MessageInfos:      file_proto_services_pages_software_page_proto_msgTypes,
	}.Build()
	File_proto_services_pages_software_page_proto = out.File
	file_proto_services_pages_software_page_proto_rawDesc = nil
	file_proto_services_pages_software_page_proto_goTypes = nil
	file_proto_services_pages_software_page_proto_depIdxs = nil
}
